### ISSUE TITLE
Doesnt Save 

### ISSUE THREAD

**Issue by AdrianoGama** [qbcore-framework/qb-tunerchip#20]
When you use the tunerlaptop and set all to max when i save the car in the garage and remove it again doesnt save and lose the tune

**Comment by Synthethics** [comment]
Valid issue. When saving the car to the garage, the tune is removed and you have to re-do the tune.

**Comment by SlugTeamSix** [comment]
IMO this is preferential behavior, it allows for more RP, otherwise every car will be tuned eventually and no one will need to come back for a tune or desire to even procure a tuner laptop to use on their own cars when one person can perma-tune it. Totally subjective and just my opinion though.

**Comment by Synthethics** [comment]
> IMO this is preferential behavior, it allows for more RP, otherwise every car will be tuned eventually and no one will need to come back for a tune or desire to even procure a tuner laptop to use on their own cars when one person can perma-tune it. Totally subjective and just my opinion though.

I wouldn't call it having more RP other than pissing people off and having to visit a mechanic each time you park your car in a garage, which seems to be very frequent. Even in real life tuning is permanent and not a one-time thing that would reset once you turn your engine off. Just my two cents.

**Comment by SlugTeamSix** [comment]
Totally valid, I get that what I'm saying is just my two cents as well, I can just envision everyone being permatuned and then the chip gets pointless, but if there is a way for cops to wipe tunes when cars are impounded or something like that, that could be a good way to encourage RP without pissing people off who simply store their vehicles. Or a save tune config could be nice. But I definitely get where you're coming from.

**Comment by Zy0exe** [comment]
You can always try to save the tune in an array and save it in the db.

**Comment by WrecksBG** [comment]
How we can array ?
