### ISSUE TITLE
NOS overwrites handling

### ISSUE THREAD

**Issue by adweex** [qbcore-framework/qb-tunerchip#23]
Sentinel without nitrous. Tested on sandy airport
Speed end of the line: 152kmph

Sentinel with installed nitrous
Speed end of the line: 178 kmph

How to reproduce:
Spawn 2 sentinel (or any kind of car). You must install nitrous in one of the cars. Use it at least for 1 second. The moment you used your Nitrous, the handling is overwritten. Do a race, and it will the car with nitrous will be much more faster without using the nitrous.

Even if you deplete your nitrous oxide the car you used nitrous on will be much more faster than any other car.

I did a report on Tuner chip too, please check it as well.

**Comment by CostaMorales** [comment]
Got the same Problem. Is there any way to fix this?
