### ISSUE TITLE
NOS issue

### ISSUE THREAD

**Issue by roobr** [qbcore-framework/qb-tunerchip#4]
Hello, 

I seem to be having an issue with the NOS function, 

When adding nos to the car if you use it for more than about 3 seconds the hud stops counting down and you have infinite boost until you stop using the nitrous and re-engage the nitrous button.

https://youtu.be/mlzZytlNgWs

**Comment by ihyajb** [comment]
its not infinite but I do get the same issue, eventually it gets to 0 and the NOS stops

**Comment by roobr** [comment]
I have had some feedback from my testers, it seems that it is more likely
after 80mph (I think it’s mph) and until you let go it will keep going as
long as you want.

**Comment by GhzGarage** [comment]
Fixed - https://github.com/qbcore-framework/qb-tunerchip/commit/a4030661e1128a82972224f79100f104afe86017
