### ISSUE TITLE
[BUG] Stancer not functional?

### ISSUE THREAD

**Issue by XeroxTEMPA** [qbcore-framework/qb-tunerchip#41]
**Describe the bug**
Stancing options do absolutely nothing. Even after saving.
**To Reproduce**
1. Open the tuner menu
2. Go to the stancing options
3. Attempt to make a change.

**Expected behavior**
Vehicle wheel position moves

**Questions (please complete the following information):**
 - When you last updated: last week
 - Are you using custom resource? no
 - Have you renamed `qb-` to something custom? no

**Comment by TonybynMp4** [comment]
You need vstancer for those to work

**Comment by AdamAtomus** [comment]
> You need vstancer for those to work

yeah I have it installed and it also does nothing. 
![image](https://user-images.githubusercontent.com/42122290/197954648-e40e536b-10b0-4480-835c-7f4d46a1b3e7.png)

**Comment by Killerhunter100** [comment]
> 

make sure that vstancer is working good

**Comment by davoucci** [comment]
somebody can give me the right link to download the vstancer to make it work?

**Comment by 0xtasty** [comment]
@davoucci https://github.com/carmineos/fivem-vstancer
