### ISSUE TITLE
[BUG] I can't use nitro

### ISSUE THREAD

**Issue by p3dr0jsm2** [qbcore-framework/qb-tunerchip#44]
Basically I use nitro and it appears it is connecting the nos but then I can't use it

**Comment by tom-osborne** [comment]
@p3dr0jsm2 do you have any script that may be disabling the CTRL key while in a vehicle? This is commonly caused by users adding in code that prevents users from "tilting" the vehicle while in mid-air.

If so, then I advise changing the NOS key to shift as that is usually not disabled.

**Comment by p3dr0jsm2** [comment]
Thanks! Changing the key really worked. Thanks again.

**Comment by tom-osborne** [comment]
@p3dr0jsm2 There is also a [PR](https://github.com/qbcore-framework/qb-tunerchip/pull/38) that may fix the issue and keep CTRL as the key. If you could test that, it would be appreciated. If not, no worries, glad you got it fixed.
