### ISSUE TITLE
NOS OneSync Issue

### ISSUE THREAD

**Issue by GodJami** [qbcore-framework/qb-tunerchip#5]
Hey there
Noticed that this error shows up when the person uses NOS outside of your OneSync area: https://imgur.com/oav3nH6
If the person is close, in your area, it doesn't error. Nos keeps working just fine for everyone no matter how far away.

**Comment by GhzGarage** [comment]
Fixed - https://github.com/qbcore-framework/qb-tunerchip/commit/a4030661e1128a82972224f79100f104afe86017
