### ISSUE TITLE
[BUG] Nitro doesn't work?

### ISSUE THREAD

**Issue by Ivofy** [qbcore-framework/qb-tunerchip#53]
Hello!

Downloaded latest qb-tunerchip and my "nitrous" doesn't work. Tried every keybind and stuff.
Or it need some dependencys?

Thanks!

**Comment by tom-osborne** [comment]
Nitrous works by using the `nitrous` item while in a vehicle to install nitrous to your vehicle. You then enable nitrous by pressing the CTRL key.

If CTRL is not working, check you don't have any resources that are diabling the control key while in a vehicle.
