### ISSUE TITLE
[SUGGESTION] Change the way NOS works

### ISSUE THREAD

**Issue by nzkfc** [qbcore-framework/qb-tunerchip#57]
**Is your feature request related to a problem? Please describe.**
If using NOS, you have to either hold it down and use a full tank, or if you let go say halfway, the tank goes into a configurable cooldown period, to stop people spamming NOS.

**Describe the feature you'd like**
- Add config.noscooldowntimer = 30 -- In seconds
- Make it so you can either hold down CTRL to use up all of the tank, or if you let go, a cooldown timer applies with a locale to validate that "You need to wait for the NOS system to cooldown!" or somehting.

**Describe alternatives you've considered**
Tried to disable spam use but doesn't work to my LUA knowledge.

**Additional context**
N/A

**Comment by Bakisito** [comment]
@nzkfc Done!
