### ISSUE TITLE
[Bug] Inifnite nos and kicked off the server 

### ISSUE THREAD

**Issue by ImpulseFPS** [qbcore-framework/qb-tunerchip#6]
Bug: Inifinity nos boost, server not registering the amount of nos left properly, getting kicked off the server for network overflow.

Reproduction: use nos hold down LCTRL until https://prnt.sc/1qb2qdg 😄 .

Fix: No solution found on my end for now

**Comment by ImpulseFPS** [comment]
Isolated the issue with people getting kicked off the server on new server artifact's
The issue is happening with the frame sync server event on the client-side the loop is spamming the server with event trigger which causes the server to kick that player off for spamming the server lmao.. kinda confusing tbh but basically this loop should be re-coded so that server is not get spammed by the player with event trigger
`lua
Citizen.CreateThread(function()
    while true do
        if NitrousActivated then
            local veh = GetVehiclePedIsIn(PlayerPedId())
            TriggerServerEvent('nitrous:server:SyncFlames', VehToNet(veh))
            SetVehicleBoostActive(veh, 1)
            StartScreenEffect("RaceTurbo", 0.0, 0)

            for _,bones in pairs(p_flame_location) do
                if GetEntityBoneIndexByName(veh, bones) ~= -1 then
                    if Fxs[bones] == nil then
                        RequestNamedPtfxAsset(ParticleDict)
                        while not HasNamedPtfxAssetLoaded(ParticleDict) do
                            Citizen.Wait(0)
                        end
                        SetPtfxAssetNextCall(ParticleDict)
                        UseParticleFxAssetNextCall(ParticleDict)
                        Fxs[bones] = StartParticleFxLoopedOnEntityBone(ParticleFx, veh, 0.0, -0.02, 0.0, 0.0, 0.0, 0.0, GetEntityBoneIndexByName(veh, bones), ParticleSize, 0.0, 0.0, 0.0)
                    end
                end
            end
        end
        Citizen.Wait(0)
    end
end)
`

**Comment by notapteryx** [comment]
Your issue might be the fact that thread is running each frame. In the default code it sleeps the thread for 100ms.

**Comment by GhzGarage** [comment]
Fixed  - https://github.com/qbcore-framework/qb-tunerchip/commit/a4030661e1128a82972224f79100f104afe86017

**Comment by zeemkarry** [comment]
I have the same problem, server kick my players if they use nos
