### ISSUE TITLE
Current issues

### ISSUE THREAD

**Issue by notapteryx** [qbcore-framework/qb-tunerchip#8]
- If you jump out of the car while using nitrous the race effect continues
- Anyone in the vehicle can load and use NOS even if there is already NOS in the vehicle
- On the thread that syncs the fames starting on line 184 if the vehicle is nil an error is thrown because it attempts to add particle effects to a bone it cannot index.
- Similar issue on line 214 where the client portion of the SyncFlames event is declared.
- vStancer export is old, and isn't a function anymore in the current build of vStancer.

**Comment by notapteryx** [comment]
Created a pull request to fix outlined issues

**Comment by GhzGarage** [comment]
I pushed your update with a minor modification thank you!
